services:
  db_container:
    image: postgis/postgis:16-3.4-alpine
    container_name: db_container
    restart: unless-stopped
    env_file: "config.env"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_HOST_PORT:-6969}:${DB_CONTAINER_PORT:-5432}"

volumes:
  pgdata: